apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infra
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/bernardolsp/azure-studies.git
      revision: HEAD
      directories:
      - path: "external-dns/"
  template:
    metadata:
      name: '{{path[0]}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/bernardolsp/azure-studies.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - "./values.yml"
      destination:
        server: https://kubernetes.default.svc
